version: "3"

services:
  external:
    container_name: splitgram
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Rome
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${APP_PORT:-3000}:3000